### ISSUE TITLE
Semantic versioning

### ISSUE THREAD

**Issue by jactor-rises** [navikt/bidrag-beregn-felles#22]
oppgradering av `bidrag-beregn-felles` i `bidrag-beregn-bidragsevne-rest` kompilerer ikke med:
```
[ERROR] Failed to execute goal org.jetbrains.kotlin:kotlin-maven-plugin:1.3.72:compile (compile) on project bidrag-beregn-bidragsevne-rest: Compilation failure
[ERROR] /Users/jactor/ws/bidrag-beregn-bidragsevne-rest/src/main/kotlin/no/nav/bidrag/beregn/bidragsevne/rest/dto/http/dtos.kt:[49,3] No value passed for parameter 'sjablonPeriodeListeNy'
```

Følgende er rutiner for semantisk versjonering:
* patch version `0.0.x`: Oppgradering av `x` er bakoverkompatibel og skal ikke forårsake kompileringsfeil
* minor version `0.x.0`: Oppgradering av `x` betyr at det er lagt til nye ting i api, men alt skal være bakoverkompatibelt og ikke forårsake kompileringsfeil
* major version `x.0.0`: Oppgradering av `x` betyr at eksisterende api er endret. Dette medfører som oftest kompileringsfeil og er en endring, sletting eller tillegg til eksisterende api som er påkrevd...

**Comment by jactor-rises** [comment]
@LarsOttoHaugen og @rinnan17 ... det kan diskutets om dette skal opp i major version. dette skal bare være må-krav når versjonen har gått i prod, men patch-version skal uansett være bakoverkompatibel

**Comment by LarsOttoHaugen** [comment]
Hvor er det du ser at bidrag-beregn-bidragsevne-rest ikke kompilerer? Ligger det automatisk sjekk av det?

**Comment by jactor-rises** [comment]
når jeg prøver å oppgradere versjon av felles fra `0.1.7` til `0.1.9`...

**Comment by LarsOttoHaugen** [comment]
Blir litt surr fordi jeg har en branch på bidrag-beregn-bidragsevne-rest også som ikke er merget. Men dette burde nok egentlig vært en minor-versjon, ja. Skal rydde opp i morgen. Enig i at vi bør være mer bevisst på versjonering; problemet er at det fort blir inflasjon i versjoner (dette er egentlig første del av en større rettelse). Foreslår vi venter med major version til vi går i prod.

**Comment by LarsOttoHaugen** [comment]
Jeg har endret til minor versjon (0.2.0)
