### ISSUE TITLE
Kun legge ut sjabloner som faktisk blir brukt i resultatGrunnlag

### ISSUE THREAD

**Issue by LarsOttoHaugen** [navikt/bidrag-beregn-felles#28]
Alle forekomster av en gitt sjablontype innenfor en gitt tidsperiode blir pt. lagt ut i resultatgrunnlaget uansett om de faktisk blir brukt eller ikke. Vil f.eks. føre til at alle forekomster av SjablonTall legges ut. Bør endres slik at kun de forekomstene som faktisk brukes legges ut. Dette må trolig gjøres i Bidragsevneberegning. Alternativt gjøre det mer generisk ifbm sjablonoppsett ved at det gjøres en filtrering i forkant av beregning, men tror det blir komplisert å få til.

**Comment by rinnan17** [comment]
Antar at dette vil være aktuelt for alle beregninger, ikke bare bidragsevneberegning

**Comment by rinnan17** [comment]
done
